#!/bin/bash
set -euo pipefail

function putItem() {
  LOCALSTACK_HOST=localhost \
  awslocal \
    dynamodb \
    put-item \
    --table-name weight-samples \
    --item "$1"
}

this_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $this_dir)

cd $repo_dir
putItem '{"date": {"S": "2018-01-05"}, "value": {"N": "1.0"}}'
putItem '{"date": {"S": "2018-01-04"}, "value": {"N": "2.0"}}'
putItem '{"date": {"S": "2018-01-03"}, "value": {"N": "3.0"}}'
putItem '{"date": {"S": "2018-01-02"}, "value": {"N": "4.0"}}'
putItem '{"date": {"S": "2018-01-01"}, "value": {"N": "5.0"}}'
