#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $this_dir)

cd $repo_dir
LOCALSTACK_HOST=localhost \
awslocal \
  dynamodb \
  create-table \
  --table-name weight-samples \
  --attribute-definitions \
  AttributeName=date,AttributeType=S \
  --key-schema \
  AttributeName=date,KeyType=HASH \
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
